# Generated by Django 6.0.4 on 2026-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='CraveCast Binangonan', max_length=255)),
                ('contact_number', models.CharField(default='09123456789', max_length=20)),
                ('stock_threshold', models.IntegerField(default=20)),
                ('weather_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('forecast_mode', models.CharField(choices=[('Standard', 'Standard'), ('Aggressive', 'Aggressive'), ('Conservative', 'Conservative')], default='Standard', max_length=20)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
