# Generated by Django 6.0.4 on 2026-04-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='store_lat',
            field=models.FloatField(default=14.4667),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='store_lon',
            field=models.FloatField(default=121.1833),
        ),
    ]
