# Generated by Django 6.0.4 on 2026-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_salesuploadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerevent',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
