# Generated by Django 6.0.4 on 2026-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_ownerevent_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
