# Generated by Django 6.0.4 on 2026-09-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_eventrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ownerevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
