# Generated by Django 6.0.4 on 2026-06-12 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_event_created_at_event_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual / Seeded'), ('low_stock', 'Auto – Low Stock'), ('best_seller', 'Auto – Best Seller')], default='manual', max_length=20)),
                ('linked_item', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-priority', 'title'],
                'unique_together': {('title', 'date')},
            },
        ),
    ]
