# Generated by Django 6.0.4 on 2026-09-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_preptask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
