# Generated by Django 6.0.4 on 2026-05-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_archived',
            new_name='can_export',
        ),
    ]
