# Generated by Django 6.0.4 on 2026-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_archived_user_can_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock / Restock'), ('expired', 'Expired Stock'), ('expiring', 'Expiring Soon'), ('approval', 'Approval'), ('contract', 'Contract Expiring'), ('upload', 'CSV Upload'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
