# Generated by Django 6.0.4 on 2026-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock / Restock'), ('expired', 'Expired Stock'), ('expiring', 'Expiring Soon'), ('predicted_shortage', 'Predicted Shortage'), ('approval', 'Approval'), ('rejected', 'Request Rejected'), ('restock', 'Restock'), ('contract', 'Contract Expiring'), ('upload', 'CSV Upload'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
