# Generated by Django 6.0.4 on 2026-04-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('initial_stock', models.IntegerField(max_length=7)),
                ('current_stock', models.IntegerField(max_length=7)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
