# Generated by Django 6.0.4 on 2026-04-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='initial_stock',
            field=models.IntegerField(),
        ),
    ]
