# Generated by Django 6.0.4 on 2026-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('initial_stock', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
