# Generated by Django 6.0.4 on 2026-04-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
