# Generated by Django 6.0.4 on 2026-04-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('total_stock', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Stock', 'Stock'), ('Supply', 'Supply')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
