# Generated by Django 6.0.4 on 2026-05-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_serving', models.FloatField(help_text='Amount used per 1 cup/serving')),
                ('inventory_item', models.ForeignKey(limit_choices_to={'category': 'Stock'}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.inventory')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.productrecipe')),
            ],
            options={
                'unique_together': {('recipe', 'inventory_item')},
            },
        ),
    ]
