# Generated by Django 6.0.4 on 2026-05-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryRequest',
        ),
    ]
