# Generated by Django 6.0.4 on 2026-06-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_delete_inventoryrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='restock_threshold',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Stock', 'Ingredient (Stock)'), ('Supply', 'Supply')], default='Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_stock',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('initial', 'Initial Entry'), ('restock', 'Restock'), ('deduct', 'Auto-Deduct'), ('waste', 'Waste / Spoilage')], max_length=20)),
                ('qty_change', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.inventory')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
