# Generated by Django 6.0.4 on 2026-09-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_preptask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrepTask',
        ),
    ]
