# Generated by Django 6.0.4 on 2026-09-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_delete_preptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='max_stock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryauditlog',
            name='packages',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryauditlog',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryauditlog',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryauditlog',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
