# Generated by Django 6.0.4 on 2026-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_max_stock_inventory_package_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='package_unit',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('pack', 'Pack'), ('sachet', 'Sachet'), ('bottle', 'Bottle'), ('case', 'Case'), ('roll', 'Roll'), ('bundle', 'Bundle'), ('piece', 'Piece')], default='', max_length=20),
        ),
    ]
