# Generated by Django 6.0.4 on 2026-09-29 18:16

from django.db import migrations, models
from django.utils import timezone


def backfill_stock_as_of(apps, schema_editor):
    # Existing stock levels are treated as counted on the day this runs, so
    # only sales from here on auto-deduct from them.
    Inventory = apps.get_model('inventory', 'Inventory')
    Inventory.objects.filter(stock_as_of__isnull=True).update(stock_as_of=timezone.localdate())


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventory_package_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='action',
            field=models.CharField(choices=[('initial', 'Initial Entry'), ('restock', 'Restock'), ('deduct', 'Auto-Deduct'), ('waste', 'Waste / Spoilage'), ('count', 'Stock Count Correction')], max_length=20),
        ),
        migrations.RunPython(backfill_stock_as_of, migrations.RunPython.noop),
    ]
