# Generated by Django 6.0.4 on 2026-04-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_sales', models.CharField()),
                ('monthly_sales', models.IntegerField()),
                ('weekly_sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_historu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_created=True)),
                ('product_detail', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_point', models.CharField(max_length=10)),
            ],
        ),
    ]
