# Generated by Django 6.0.4 on 2026-04-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_historu',
            new_name='Transaction_history',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='monthly_sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='weekly_sales',
        ),
    ]
