# Generated by Django 6.0.4 on 2026-04-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_transaction_historu_transaction_history_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
