# Generated by Django 6.0.4 on 2026-04-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Transaction_history',
        ),
    ]
