# Generated by Django 6.0.4 on 2026-04-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='temp_c',
            field=models.FloatField(default=30.0),
        ),
    ]
